:Author: nobodylikeswasps
:Email: {AuthorEmail}
:Date: 08/12/2019
:Revision: version#
:License: Public Domain

= Project: {Project}

Go the distance game using Arduino Leonardo

Components:

Arduino Leonardo
Ultrasonic distance sensors
LCD screen
Breadboards/wires/resistor
Pushbutton

****************************

How to play: 

When the pushbutton is pushed, a random number between 5cm - 30cm will appear on the LCD screen.
If an object moves within 70cm or closer from the ultrasonic sensor, the timer will begin.
You have 3 seconds to reach the distance displayed on the LCD screen to score a point.
Keep pushing button once previous is completed to continue increasing score.
If you take longer than 3 seconds, game will stop and your score will reset to 0.

Have fun! :)

*****************************

== Step 1: Installation
Download the .ino file, and it is only optimized to be done using the arduino web editor, NOT the IDE.

== Step 2: Load the code

Copy and paste into web editor, plug in your arduino, and play!
Timer difficulty can be changed from 3 seconds easily.

=== Contributing
To contribute to this project please contact nobodylikeswasps https://id.arduino.cc/nobodylikeswasps

I am nobodylikeswasps, you can do whatever you wish with the project.


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
